name: MSAbuilder
channels:
  - agat
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - mamba
  - gcc
  - python=3.9
  - snakemake
  - biopython
  - gffread
  - mafft
  - iqtree
  - miniprot
  - spaln
  - matplotlib
  - pandas
  - agat
  - pip
